### ISSUE TITLE
1.2.6升级到1.2.7问题

### ISSUE THREAD

**Issue by knightxing** [branchzero/yapi-docker#3]
我直接用了你了dockerfile文件，自己在本地build镜像，出现了很多问题，不知道你有没有呢

**Comment by branchzero** [comment]
没有哦，可以正常用，Docker Hub上build也没见遇到问题呀。
如果说有问题的话，就是root权限下对data目录要设置非root用户，否则mongo以及yapi的相关文件会无法写入。。（不过这不是镜像问题，是docker-compose启动时的问题）
