### ISSUE TITLE
docker-compose up 直接报错, 貌似无法连接

### ISSUE THREAD

**Issue by KISSMonX** [branchzero/yapi-docker#7]
![image](https://user-images.githubusercontent.com/2876745/38657439-ceaf4422-3e52-11e8-899d-7e163a1f53d7.png)

![image](https://user-images.githubusercontent.com/2876745/38657450-d7db2c3c-3e52-11e8-84ad-89883e2a4545.png)

**Comment by branchzero** [comment]
mount的mongodb的数据目录权限问题，这个问题很早之前我遇到过，后面给文件夹设置正确权限后再起就解决了
