### ISSUE TITLE
在config.json设置账号密码如何生效

### ISSUE THREAD

**Issue by Vickey-Wu** [branchzero/yapi-docker#9]
{
  "port": "3000",
  "adminAccount": "admin@admin.com",
  "db": {
    "servername": "mongodb",
    "DATABASE":  "yapi",
    "port": 27017,
    "user": "root",
    "pass": "123"
  },
  "mail": {
    "enable": true,
    "host": "smtp.163.com",
    "port": 465,
    "from": "***@163.com",
    "auth": {
        "user": "***@163.com",
        "pass": "*****"
    }
  }
}

你好，请问在config.json设置了账号密码，要修改哪里让它生效

**Comment by branchzero** [comment]
config.json是直接mount到容器内部的，修改之后应该直接生效的

**Comment by Vickey-Wu** [comment]
我试了几次没成功，后来将"enable": false,后就可以了
